name: 'Setup Node.js and install npm dependencies'
description: 'Configures Node.js, uses optimal caching, and installs deps efficiently.'
inputs:
    node-version:
        description: 'Node.js version to use (optional, fallback to .nvmrc)'
        required: false

runs:
    using: 'composite'
    steps:
        - name: Setup Node.js with built-in npm cache
          uses: actions/setup-node@v3
          with:
              node-version-file: '.nvmrc'
              node-version: ${{ inputs.node-version }}
              cache: 'npm' # Caches ~/.npm

        - name: Output Node and npm versions
          shell: bash
          run: |
              echo "✅ Node version: $(node -v)"
              echo "✅ npm version: $(npm -v)"

        - name: Install npm dependencies
          shell: bash
          run: |
              echo "⚡ Installing dependencies using npm ci"
              npm ci --legacy-peer-deps --prefer-offline --no-audit
