name: 'Setup Node.js and install npm dependencies'
description: 'Configure Node.js and install all npm dependencies with cache and flexible engine handling.'
inputs:
    node-version:
        description: 'Optional. The Node.js version to use. When not specified, uses version from .nvmrc'
        required: false

runs:
    using: 'composite'
    steps:
        - name: Use desired version of Node.js
          uses: actions/setup-node@v3
          with:
              node-version-file: '.nvmrc'
              node-version: ${{ inputs.node-version }}
              cache: 'npm'

        - name: Set faster registry
          run: npm config set registry https://registry.npmmirror.com
          shell: bash

        - name: Output Node.js version
          run: echo "Using Node $(node -v) and npm $(npm -v)"
          shell: bash

        - name: Install npm dependencies (with legacy peer deps)
          run: npm install --legacy-peer-deps
          shell: bash
