name: 'Setup Node.js and install npm dependencies'
description: 'Configure Node.js, install dependencies, and handle Puppeteer installation safely for CI.'
inputs:
    node-version:
        description: 'Optional. The Node.js version to use. When not specified, the version specified in .nvmrc will be used.'
        required: false

runs:
    using: 'composite'
    steps:
        - name: Use desired version of Node.js
          uses: actions/setup-node@v3
          with:
              node-version-file: '.nvmrc'
              node-version: ${{ inputs.node-version }}
              cache: 'npm'

        - name: Downgrade npm to v8.19.3
          run: npm install -g npm@8.19.3
          shell: bash

        - name: Confirm Node and npm versions
          run: |
              echo "✅ Node version: $(node -v)"
              echo "✅ npm version: $(npm -v)"
          shell: bash

        - name: Set faster npm registry
          run: npm config set registry https://registry.npmmirror.com
          shell: bash

        - name: Install npm dependencies (skip Chromium during install)
          run: npm install --legacy-peer-deps --verbose
          shell: bash
          env:
              PUPPETEER_SKIP_DOWNLOAD: 'true'

        - name: Manually install Chromium for Puppeteer
          run: node .github/scripts/install-puppeteer.cjs
          shell: bash
