name: 'Setup Node.js and install npm dependencies'
description: 'Configure Node.js and install npm dependencies while managing all aspects of caching.'
inputs:
    node-version:
        description: 'Optional. The Node.js version to use. When not specified, the version specified in .nvmrc will be used.'
        required: false

runs:
    using: 'composite'
    steps:
        - name: Use desired version of Node.js
          uses: actions/setup-node@v3
          with:
              node-version-file: '.nvmrc'
              node-version: ${{ inputs.node-version }}
              cache: 'npm'

        - name: Downgrade npm to v8.19.3
          run: npm install -g npm@8.19.3
          shell: bash

        - name: Confirm Node and npm versions
          run: |
              echo "Node: $(node -v)"
              echo "npm: $(npm -v)"
          shell: bash

        - name: Install npm dependencies
          run: npm install --legacy-peer-deps --verbose
          shell: bash
