name: Build Of Library (zip file)
run-name: ${{ github.actor }} zip file 🤐
on:
    push:
    pull_request:
jobs:
    composer-install:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: composer install --ansi --no-progress --no-interaction --prefer-dist
            - uses: montudor/action-zip@v1
              with:
                  args: zip -qq -r vendor.zip vendor
            - uses: actions/upload-artifact@v2
              with:
                  name: vendor.zip
    tests:
        needs: composer-install
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/download-artifact@v2
              with:
                  name: vendor.zip
            - uses: montudor/action-zip@v1
              with:
                  args: unzip -qq vendor.zip -d vendor
            - run: ./vendor/bin/phpunit
    mutation:
        needs: composer-install
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/download-artifact@v2
              with:
                  name: vendor.zip
            - uses: montudor/action-zip@v1
              with:
                  args: unzip -qq vendor.zip -d vendor
            - run: ./vendor/bin/infection
