name: Check for Debugging Code

on:
    pull_request:
        types: [opened, synchronize, ready_for_review]

jobs:
    check-debugging:
        name: Check for Debugging Code
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Check for Debugging Code
              run: |
                  # Initialize error flag
                  FOUND_ERRORS=0

                  echo "Checking PHP files for debugging code..."
                  echo "============================================"
                  while IFS= read -r file; do
                    if [[ "$file" == *"tests/"* ]]; then continue; fi
                    if grep -n -E "(die\(|var_dump\(|print_r\(|error_log\(|wp_die\(|exit\()" "$file" | while IFS=: read -r line_number line; do
                      if ! grep -A1 -B1 -n "$line" "$file" | grep -q "@debug-ignore"; then
                        echo "⚠️ Found PHP debugging code:"
                        echo "📁 File: $file"
                        echo "📍 Line: $line_number"
                        echo "📝 Code: $line"
                        echo "----------------------------------------"
                        FOUND_ERRORS=1
                      fi
                    done; then :; fi
                  done < <(find . -type f -name "*.php")

                  echo "Checking JavaScript/TypeScript files for debugging code..."
                  echo "============================================"
                  while IFS= read -r file; do
                    if [[ "$file" == *"tests/"* ]]; then continue; fi
                    if grep -n -E "(console\.(log|debug|info|warn|error)|debugger|alert\()" "$file" | while IFS=: read -r line_number line; do
                      if ! grep -A1 -B1 -n "$line" "$file" | grep -q "@debug-ignore"; then
                        echo "⚠️ Found JavaScript debugging code:"
                        echo "📁 File: $file"
                        echo "📍 Line: $line_number"
                        echo "📝 Code: $line"
                        echo "----------------------------------------"
                        FOUND_ERRORS=1
                      fi
                    done; then :; fi
                  done < <(find . -type f \( -name "*.js" -o -name "*.jsx" -o -name "*.ts" -o -name "*.tsx" \))

                  echo "Checking test files for .skip/.only..."
                  echo "============================================"
                  while IFS= read -r file; do
                    if [[ "$file" == *"tests/"* ]]; then continue; fi
                    if grep -n -E "\.(skip|only)\(" "$file" | while IFS=: read -r line_number line; do
                      if ! grep -A1 -B1 -n "$line" "$file" | grep -q "@debug-ignore"; then
                        echo "⚠️ Found test skip/only:"
                        echo "📁 File: $file"
                        echo "📍 Line: $line_number"
                        echo "📝 Code: $line"
                        echo "----------------------------------------"
                        FOUND_ERRORS=1
                      fi
                    done; then :; fi
                  done < <(find . -type f -name "*.test.*")

                  # Final status check
                  if [ $FOUND_ERRORS -eq 1 ]; then
                    echo "❌ Found debugging code that needs to be removed or marked with @debug-ignore"
                    exit 1
                  else
                    echo "✅ No unauthorized debugging code found"
                    exit 0
                  fi
