name: Cypress Components Tests

on:
    pull_request:
        types: [opened, synchronize, ready_for_review]

    workflow_dispatch:

jobs:
    cypress_components_tests:
        name: Cypress Components Tests
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'blockeraai/blockera' || github.event_name == 'pull_request' }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Node.js and install dependencies
              uses: ./.github/setup-node

            - name: Install Cypress
              run: npx cypress install

            - name: Run Cypress Tests
              run: npm run test:ct
