name: Cypress E2E Tests

on:
    pull_request:
        types: [opened, synchronize, ready_for_review]

    workflow_dispatch:

jobs:
    cypress_e2e_tests:
        name: Cypress End 2 End Tests
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'blockeraai/blockera' || github.event_name == 'pull_request' }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Node.js and install dependencies
              uses: ./.github/setup-node

            - name: Install Cypress
              run: npx cypress install

            - name: Install Composer Packages
              run: composer install --no-dev -o --apcu-autoloader -a

            - name: Start WordPress Environment
              run: npm run env:start

            - name: 'Create env file'
              run: |
                  touch .env
                  echo APP_MODE=production >> .env
                  echo DB=wp_tests >> .env
                  cat .env

            - name: Build wp-env app
              run: npm run build

            - name: Remove .env file
              run: rm -rf .env

            - name: Run Cypress E2E Tests
              run: npm run test:e2e

            - name: Stop WordPress Environment
              run: npm run env:stop
